# Generated by Django 6.0.2 on 2026-02-14 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Featured Video', max_length=200)),
                ('youtube_url', models.URLField(help_text='Enter YouTube video URL')),
                ('youtube_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('autoplay', models.BooleanField(default=False)),
                ('mute', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage Video',
                'verbose_name_plural': 'Homepage Videos',
            },
        ),
    ]
