# Generated by Django 6.0.2 on 2026-02-22 03:03

import embed_video.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_homepagevideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagevideo',
            name='youtube_id',
        ),
        migrations.RemoveField(
            model_name='homepagevideo',
            name='youtube_url',
        ),
        migrations.AddField(
            model_name='homepagevideo',
            name='video',
            field=embed_video.fields.EmbedVideoField(default='', help_text='Enter YouTube, Vimeo, or SoundCloud URL'),
            preserve_default=False,
        ),
    ]
