# Generated by Django 6.0.2 on 2026-02-22 07:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_blogpost_options_blogpost_excerpt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('date_taken', models.DateField(default=django.utils.timezone.now)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
            ],
            options={
                'verbose_name_plural': 'Gallery Photos',
                'ordering': ['display_order', '-date_taken'],
            },
        ),
    ]
